---
- name: Download Puppet 5 release package for Focal (Agent)
  get_url:
    url: https://apt.puppetlabs.com/puppet5-release-focal.deb
    dest: /tmp/puppet5-release-focal.deb
    mode: '0644'

- name: Install Puppet 5 release package for Focal (Agent)
  apt:
    deb: /tmp/puppet5-release-focal.deb
  become: true

- name: Update apt cache (Agent)
  apt:
    update_cache: yes
  become: true

- name: Install Puppet Agent
  apt:
    name: puppet-agent
    state: present
  become: true

- name: Configure Puppet Agent settings
  template:
    src: templates/puppet_agent.conf.j2
    dest: /etc/puppetlabs/puppet/puppet.conf
    mode: '0644'
  notify: restart puppet agent
- name: Start and enable Puppet Agent service
  service:
    name: puppet
    state: started
    enabled: yes
- name: Run initial Puppet run
  command: puppet agent -t
