[puppet_servers]
puppet.example.com ansible_host=puppetserver ansible_user=vagrant

[puppet_agents]
puppetagent01.example.com ansible_host=puppetagent0_1 ansible_user=vagrant
puppetagent02.example.com ansible_host=puppetagent0_2 ansible_user=vagrant
