---
- name: Download Puppet 5 release package for Focal
  get_url:
    url: https://apt.puppetlabs.com/puppet5-release-focal.deb
    dest: /tmp/puppet5-release-focal.deb
    mode: '0644'

- name: Install Puppet 5 release package for Focal
  apt:
    deb: /tmp/puppet5-release-focal.deb
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install Puppet Server and supporting packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - puppetserver
    - puppetdb
    - puppetdb-termini
    - git
    - tree
  become: true

- name: Enable and start Puppet Server services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - puppetserver
    - puppetdb
- name: Configure Puppet Server memory
  replace:
    path: /etc/default/puppetserver
    # This regex looks for -Xm[sx]<digits>g (e.g., -Xms2g or -Xmx4g)
    # and changes the <digits> part to 1, effectively setting it to 1g.
    # This will affect both -Xms and -Xmx if they are present and match the pattern.
    regexp: '(-Xm[sx])([0-9]+)g'
    replace: '\11g'
  notify: restart puppetserver
- name: Configure Puppet Server settings
  template:
    src: templates/puppet.conf.j2
    dest: /etc/puppetlabs/puppet/puppet.conf
    mode: '0644'
  notify: restart puppetserver
- name: Set up autosign configuration
  copy:
    content: "*.example.com"
    dest: /etc/puppetlabs/puppet/autosign.conf
    mode: '0644'
